import textwrap

def generate_setup_script(ca_pub_key):
    """
    Generates a bash script to bootstrap an SSH server with Ephemera CA.
    """
    # Escape single quotes in the key just in case, though pub keys usually don't have them.
    safe_key = ca_pub_key.strip().replace("'", "'\\''")
    
    script = f"""#!/bin/bash
set -e

# Ephemera Server Bootstrap Script
# Generated by ephemera-cli

CA_PUB_KEY='{safe_key}'
EPHEMERA_DIR="/etc/ssh/ephemera"
SSHD_CONFIG="/etc/ssh/sshd_config"
BACKUP_SUFFIX=".ephemera.bak"

# 1. Check for Root
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root."
    exit 1
fi

echo "[+] Starting Ephemera Server Setup..."

# 2. Create Directory
if [ ! -d "$EPHEMERA_DIR" ]; then
    echo "[+] Creating $EPHEMERA_DIR"
    mkdir -p "$EPHEMERA_DIR"
    chmod 755 "$EPHEMERA_DIR"
fi

# 3. Write CA Public Key
echo "[+] Installing CA Public Key to $EPHEMERA_DIR/ca_key.pub"
echo "$CA_PUB_KEY" > "$EPHEMERA_DIR/ca_key.pub"
chmod 644 "$EPHEMERA_DIR/ca_key.pub"

# 4. Create Revocation List (KRL)
if [ ! -f "$EPHEMERA_DIR/revoked.krl" ]; then
    echo "[+] Creating empty revocation list at $EPHEMERA_DIR/revoked.krl"
    touch "$EPHEMERA_DIR/revoked.krl"
    # Initialize with empty KRL if possible, or just empty file works for some versions.
    # Ideally we should generate a valid empty KRL, but an empty file is often ignored or sufficient.
    # Better: ssh-keygen -k -f "$EPHEMERA_DIR/revoked.krl" /dev/null if we had a key to revoke.
    # For now, just touch.
    chmod 644 "$EPHEMERA_DIR/revoked.krl"
fi

# 5. Backup sshd_config
if [ ! -f "$SSHD_CONFIG$BACKUP_SUFFIX" ]; then
    echo "[+] Backing up $SSHD_CONFIG to $SSHD_CONFIG$BACKUP_SUFFIX"
    cp "$SSHD_CONFIG" "$SSHD_CONFIG$BACKUP_SUFFIX"
else
    echo "[!] Backup already exists, skipping backup to preserve original state."
fi

# 6. Update sshd_config
echo "[+] Configuring $SSHD_CONFIG..."

# Helper function to set or replace a config option
set_config() {{
    local key="$1"
    local value="$2"
    if grep -q "^[#]*\s*$key" "$SSHD_CONFIG"; then
        sed -i "s|^[#]*\s*$key.*|$key $value|" "$SSHD_CONFIG"
    else
        echo "$key $value" >> "$SSHD_CONFIG"
    fi
}}

set_config "TrustedUserCAKeys" "$EPHEMERA_DIR/ca_key.pub"
set_config "RevokedKeys" "$EPHEMERA_DIR/revoked.krl"
set_config "PasswordAuthentication" "no"
set_config "ChallengeResponseAuthentication" "no"
set_config "PubkeyAuthentication" "yes"
# set_config "UsePAM" "no" # Optional, leaving default usually safer for other auth modules

# 7. Validate Config
echo "[+] Validating sshd configuration..."
if sshd -t; then
    echo "[+] Configuration valid."
else
    echo "ERROR: sshd configuration is invalid! Restoring backup..."
    cp "$SSHD_CONFIG$BACKUP_SUFFIX" "$SSHD_CONFIG"
    exit 1
fi

# 8. Reload sshd
echo "[+] Reloading sshd..."
if command -v systemctl >/dev/null 2>&1; then
    systemctl reload sshd
elif command -v service >/dev/null 2>&1; then
    service ssh reload
else
    echo "WARNING: Could not detect systemctl or service. Please reload sshd manually."
fi

echo "[SUCCESS] Server is now configured to trust Ephemera CA."
"""
    return script
